using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using TFramework.Singleton;

namespace TFramework.Utils
{
    public class LocalizationUtils : AutoGeneratedSingleton<LocalizationUtils>, IDisposable
    {
        private Dictionary<string, string> m_localizationVals = null;

        public LocalizationUtils()
        {
            m_localizationVals = new Dictionary<string, string>();
        }

        public void Init(string csvPath)
        {
            if (!File.Exists(csvPath))
            {
                return;
            }
            ReadCSVFile(csvPath);
        }

        /// <summary>
        /// KEY,Language
        /// 01,balabala...
        /// </summary>
        /// <param name="path"></param>
        private void ReadCSVFile(string path)
        {
            Dictionary<string, string> mTemp = new Dictionary<string, string>();
            mTemp.Clear();

            string[] lines = File.ReadAllLines(path, Encoding.UTF8);
            if (lines.Length <= 0)
            {
                return;
            }
            for (int i = 1; i < lines.Length; i++)
            {
                if (string.IsNullOrEmpty(lines[i]))
                {
                    continue;
                }
                int index = lines[i].IndexOf(',');
                string key = lines[i].Substring(0, index);
                string value = lines[i].Substring(index + 1, lines[i].Length - index - 1);

                mTemp.Add(key, value.Trim('"'));
            }
            m_localizationVals = mTemp;
        }

        public string Get(string key)
        {
            if (!m_localizationVals.ContainsKey(key))
            {
                return key;
            }
            return m_localizationVals[key];
        }

        public string Format(string key, params object[] parameters)
        {
            if (!m_localizationVals.ContainsKey(key))
            {
                return key;
            }
            return string.Format(Get(key), parameters);
        }

        public void Dispose()
        {
            m_localizationVals = null;
        }
    }
}
