/*
    _create: sun hai lang
    _time: 2020-03-23
 */

namespace TFramework.Singleton
{
    public class AutoGeneratedSingleton<T> where T : AutoGeneratedSingleton<T>, new()
    {
        private static T m_instance = null;
        public static readonly object _lock = new object();

        public static T Instance
        {
            get
            {
                lock (_lock)
                {
                    if (m_instance == null)
                    {
                        m_instance = new T();
                    }
                    return m_instance;
                }
            }
        }
    }
}
